# Project and environment settings
project_id: "<your-project-id>"
location: "<your-region>"

# Data and storage settings
data_path: "{base_path}/data/data"
input_bucket_name: "ken-rag-datasets"
docstore_bucket_name: "ken-rag-datasets"
bucket_prefix: "raw_pdfs/"
vector_data_prefix: "vector_data"
rag_eval_dataset: "ken-rag-datasets"
firestore_db_name: "rag-docstore"
firestore_namespace: "hierarchical_docs"

# Index settings
index_id: "llamaindex_rag"
vector_index_name: "google_hierarchical"
index_endpoint_name: "hierarchical_endpoint"
indexing_method: "hierarchical"
qa_index_name: "google_qa"
qa_endpoint_name: "hierarchical_endpoint"

# Chunking and embedding settings
chunk_sizes: [4096, 2048, 1024, 512]
chunk_size: 512
chunk_overlap: 50
embeddings_model_name: "text-embedding-004"
approximate_neighbors_count: 100

# Document AI settings
docai_location: "us"
docai_processor_id: "f1713ecadbbf91ab"
document_ai_processor_display_name: "layout-parser"
create_docai_processor: false

# Authentication
service_account_key: "llamaindex-rag"

# API settings
fastapi_url: "http://localhost:8033"

# UI settings
streamlit_host: "0.0.0.0"
streamlit_port: 8080
