name: app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.7
  font_awesome_flutter: ^10.7.0
  provider: ^6.1.2
  flutter_animate: ^4.5.0
  go_router: ^14.2.0
  firebase_vertexai: ^0.2.2
  firebase_core: ^3.1.0
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.3.1
  shimmer: ^3.0.0
  flutter_chat_ui: ^1.6.12
  uuid: ^4.4.0
  http: ^1.2.1
  firebase_auth: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
