[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"

[tool.poetry]
name = "llamaindex-rag"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "Apache License, Version 2.0"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
pyyaml = "6.0.1"
llama-index = "0.10.58"
aiohttp = "3.10.5"
aiosignal = "1.3.1"
altair = "5.3.0"
annotated-types = "0.7.0"
antlr4-python3-runtime = "4.9.3"
anyio = "4.4.0"
appdirs = "1.4.4"
asgiref = "3.8.1"
async-timeout = "4.0.3"
attrs = "24.2.0"
backoff = "2.2.1"
bcrypt = "4.1.3"
beautifulsoup4 = "4.12.3"
blinker = "1.8.2"
build = "1.2.1"
cachecontrol = "0.14.0"
cachetools = "5.4.0"
certifi = "2024.7.4"
cffi = "1.16.0"
charset-normalizer = "3.3.2"
chroma-hnswlib = "0.7.5"
chromadb = "0.5.4"
cleo = "2.1.0"
click = "8.1.7"
coloredlogs = "15.0.1"
contourpy = "1.2.1"
crashtest = "0.4.1"
cryptography = "43.0.1"
cycler = "0.12.1"
dataclasses-json = "0.6.7"
datasets = "2.20.0"
deprecated = "1.2.14"
dill = "0.3.8"
dirtyjson = "1.0.8"
distlib = "0.3.8"
distro = "1.9.0"
dnspython = "2.6.1"
docstring-parser = "0.16"
dulwich = "0.21.7"
email-validator = "2.2.0"
entrypoints = "0.4"
exceptiongroup = "1.2.2"
faker = "29.0.0"
fastapi = "0.111.1"
fastapi-cli = "0.0.4"
fastjsonschema = "2.20.0"
favicon = "0.7.0"
filelock = "3.15.4"
flatbuffers = "24.3.25"
fonttools = "4.53.1"
frozenlist = "1.4.1"
gitdb = "4.0.11"
gitpython = "3.1.43"
google-api-core = "2.19.1"
google-auth = "2.32.0"
google-cloud-aiplatform = "1.59.0"
google-cloud-bigquery = "3.25.0"
google-cloud-core = "2.4.1"
google-cloud-documentai = "2.29.2"
google-cloud-resource-manager = "1.12.4"
google-cloud-secret-manager = "2.20.1"
google-cloud-storage = "2.17.0"
google-crc32c = "1.5.0"
google-resumable-media = "2.7.1"
googleapis-common-protos = "1.63.2"
greenlet = "3.0.3"
grpc-google-iam-v1 = "0.13.1"
grpcio = "1.64.1"
grpcio-status = "1.62.2"
h11 = "0.14.0"
htbuilder = "0.6.2"
httpcore = "1.0.5"
httptools = "0.6.1"
httpx = "0.27.0"
huggingface-hub = "0.23.4"
humanfriendly = "10.0"
hydra-core = "1.3.2"
idna = "3.7"
importlib-metadata = "7.1.0"
importlib-resources = "6.4.0"
iniconfig = "2.0.0"
installer = "0.7.0"
jaraco-classes = "3.4.0"
jeepney = "0.8.0"
jinja2 = "3.1.4"
joblib = "1.4.2"
jsonpatch = "1.33"
jsonpointer = "3.0.0"
jsonschema = "4.23.0"
keyring = "24.3.1"
kiwisolver = "1.4.5"
kubernetes = "30.1.0"
langchain = "0.2.8"
langchain-community = "0.2.9"
langchain-core = "0.2.19"
langchain-google-vertexai = "1.0.6"
langchain-openai = "0.1.16"
langchain-text-splitters = "0.2.2"
langsmith = "0.1.85"
llama-cloud = "0.0.11"
llama-index-agent-openai = "0.2.9"
llama-index-cli = "0.1.13"
llama-index-core = "0.10.58"
llama-index-embeddings-openai = "0.1.11"
llama-index-embeddings-vertex = "0.1.0"
llama-index-indices-managed-llama-cloud = "0.2.6"
llama-index-legacy = "0.9.48"
llama-index-llms-openai = "0.1.27"
llama-index-llms-vertex = "0.2.2"
llama-index-multi-modal-llms-openai = "0.1.8"
llama-index-program-openai = "0.1.7"
llama-index-question-gen-openai = "0.1.3"
llama-index-readers-file = "0.1.30"
llama-index-readers-llama-parse = "0.1.6"
llama-index-vector-stores-chroma = "0.1.10"
llama-index-vector-stores-vertexaivectorsearch = "0.0.1"
llama-parse = "0.4.9"
lxml = "5.2.2"
markdown = "3.6"
markdown-it-py = "3.0.0"
markdownify = "0.13.1"
markdownlit = "0.0.7"
marko = "2.1.2"
markupsafe = "2.1.5"
marshmallow = "3.21.3"
matplotlib = "3.9.1"
mdurl = "0.1.2"
mmh3 = "4.1.0"
monotonic = "1.6"
more-itertools = "10.3.0"
mpmath = "1.3.0"
msgpack = "1.0.8"
multidict = "6.0.5"
multiprocess = "0.70.16"
mypy-extensions = "1.0.0"
nest-asyncio = "1.6.0"
networkx = "3.3"
nltk = "3.9.1"
numpy = "1.26.4"
oauthlib = "3.2.2"
omegaconf = "2.3.0"
onnxruntime = "1.18.1"
openai = "1.37.0"
opentelemetry-api = "1.25.0"
opentelemetry-exporter-otlp-proto-common = "1.25.0"
opentelemetry-exporter-otlp-proto-grpc = "1.25.0"
opentelemetry-instrumentation = "0.46b0"
opentelemetry-instrumentation-asgi = "0.46b0"
opentelemetry-instrumentation-fastapi = "0.46b0"
opentelemetry-proto = "1.25.0"
opentelemetry-sdk = "1.25.0"
opentelemetry-semantic-conventions = "0.46b0"
opentelemetry-util-http = "0.46b0"
orjson = "3.10.6"
overrides = "7.7.0"
packaging = "24.1"
pandas = "2.2.2"
pdfminer-six = "20240706"
pexpect = "4.9.0"
pillow = "10.4.0"
pkginfo = "1.11.1"
platformdirs = "4.2.2"
pluggy = "1.5.0"
poetry-core = "1.9.0"
poetry-plugin-export = "1.8.0"
posthog = "3.5.0"
prometheus-client = "0.20.0"
proto-plus = "1.24.0"
protobuf = "4.25.3"
ptyprocess = "0.7.0"
pyarrow = "15.0.2"
pyarrow-hotfix = "0.6"
pyasn1 = "0.6.0"
pyasn1-modules = "0.4.0"
pycparser = "2.22"
pydantic = "2.8.2"
pydantic-core = "2.20.1"
pydeck = "0.9.1"
pygments = "2.18.0"
pymdown-extensions = "10.8.1"
pyparsing = "3.1.2"
pypdf = "4.3.1"
pypika = "0.48.9"
pyproject-hooks = "1.1.0"
pysbd = "0.3.4"
pytest = "8.2.2"
python-dateutil = "2.9.0.post0"
python-dotenv = "1.0.1"
python-multipart = "0.0.9"
pytz = "2024.1"
ragas = "0.1.9"
rapidfuzz = "3.9.4"
referencing = "0.35.1"
regex = "2024.7.24"
requests = "2.32.3"
requests-oauthlib = "2.0.0"
requests-toolbelt = "1.0.0"
rich = "13.7.1"
rpds-py = "0.19.0"
rsa = "4.9"
secretstorage = "3.3.3"
shapely = "2.0.5"
shellingham = "1.5.4"
six = "1.16.0"
smmap = "5.0.1"
sniffio = "1.3.1"
soupsieve = "2.5"
sqlalchemy = "2.0.31"
st-annotated-text = "4.0.1"
st-theme = "1.2.3"
starlette = "0.37.2"
streamlit = "1.38.0"
streamlit-camera-input-live = "0.2.0"
streamlit-card = "1.0.2"
streamlit-embedcode = "0.1.2"
streamlit-extras = "0.4.3"
streamlit-faker = "0.0.3"
streamlit-image-coordinates = "0.1.9"
streamlit-keyup = "0.2.4"
streamlit-toggle-switch = "1.0.2"
streamlit-vertical-slider = "2.5.5"
striprtf = "0.0.26"
sympy = "1.13.0"
tenacity = "8.5.0"
tiktoken = "0.7.0"
tokenizers = "0.19.1"
toml = "0.10.2"
tomli = "2.0.1"
tomlkit = "0.13.0"
toolz = "0.12.1"
tornado = "6.4.1"
tqdm = "4.66.4"
trove-classifiers = "2024.7.2"
typer = "0.12.3"
typing-inspect = "0.9.0"
typing-extensions = "4.12.2"
tzdata = "2024.1"
urllib3 = "2.2.2"
uvicorn = "0.30.1"
uvloop = "0.19.0"
validators = "0.33.0"
virtualenv = "20.26.3"
watchdog = "4.0.1"
watchfiles = "0.22.0"
websocket-client = "1.8.0"
websockets = "12.0"
wrapt = "1.16.0"
xxhash = "3.4.1"
yarl = "1.9.4"
zipp = "3.19.2"
llama-index-storage-docstore-firestore = "^0.1.3"
llama-index-storage-index-store-firestore = "^0.1.3"
llama-index-retrievers-vertexai-search = "^0.0.1"
llama-index-retrievers-bm25 = "^0.2.2"
google-cloud-logging = "^3.11.0"
anthropic = {extras = ["vertex"], version = "^0.31.2"}
weave = "^0.50.12"
black = "^24.8.0"
flake8 = "^7.1.1"
autopep8 = "^2.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
